services:
  postgres:
    image: ablankz/postgres:1.2.0
    container_name: user-profile-postgres
    networks:
      - connect_network
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: "user_profile"
      USE_JSON_PAYLOAD_AND_HEADERS: true
      USE_DB_ID: false
      USE_SAGA: true
  register-connector:
    image: curlimages/curl:latest
    depends_on:
      - postgres
    networks:
      - connect_network
    volumes:
      - ./debezium/service-userprofile-connector-config.json:/tmp/service-userprofile-connector-config.json
    entrypoint: >
      sh -c "
        sleep 10 &&
        curl -X POST -H 'Content-Type: application/json' --data @/tmp/service-userprofile-connector-config.json http://connect:8083/connectors
      "
volumes:
  db-store:
networks:
  connect_network:
    external: true